name: clang-format

on:
  workflow_dispatch:
  push:
    branches: master
    paths-ignore:
      - 'COPYING'
      - 'README'
      - '.clang-format'
      - 'Makefile'
  pull_request:
    paths-ignore:
      - 'COPYING'
      - 'README'
      - '.clang-format'
      - 'Makefile'

jobs:
  clang-format:
    runs-on: ubuntu-26.04
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup
        run: sudo apt-get install -y clang-format-22

      - name: execute
        run: |
          CLANG_FORMAT="clang-format-19 --style=file -Werror --dry-run"
          TARGET_DIRS=("boot" "libk" "klibc")

          find "${TARGET_DIRS[@]}" \( -name "*.h" -o -name "*.c" \) -exec $CLANG_FORMAT {} +
